import java.util.List;
import java.sql.*;

import domain.*;
import repositories.*;
import repositoriesImpl.*;
public class Main {

	public static void main(String[] args) {
		String url="jdbc:hsqldb:hsql://localhost/workdb";
		User ddobek = new User();
		ddobek.setLogin("DamianDobek");
		ddobek.setPassword("admin1");
		try {
			
			Connection connection = DriverManager.getConnection(url);
			/*
			String createTableSql = 
					"CREATE TABLE users("
					+ "id int GENERATED BY DEFAULT AS IDENTITY,"
					+ "login VARECHAR(20),"
					+ "password VARCHAR(20),"
					+ ")";
			Statement createTable = connection.createStatement();
			createTable.executeUpdate(createTableSql);
			*/
			
			IRepository<User> users = new UserRepository(connection, new UserBuilder());
			users.save(ddobek);
			List<User> usersFromDb = users.getAll();
			
			for(User userFromDb: usersFromDb)
				System.out.println(userFromDb.getId()+" "+userFromDb.getLogin()+" "+userFromDb.getPassword());
			
			User a = users.get(2);
			a.setPassword("admin2");
			users.update(a);
			users.delete(usersFromDb.get(0));
			
			for(User userFromDb: users.getAll())
				System.out.println(userFromDb.getId()+" "+userFromDb.getLogin()+" "+userFromDb.getPassword());
			
			
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		
		
		System.out.println("koniec");
	}

}
